# Introduction to Numpy

We use a popular python package known as numpy, which allows for fast array data manipulation. Don't know anything about numpy? No problem, this tutorial should walk you through everything you need to know to do most of the assignments in this class.

To start, import numpy as follows.

In [1]:
import numpy as np

## Working with Numpy Arrays

Numpy uses multidimensional arrays as the core datastructure to store and manipulate values of the same type (Very similar to matrices).

To work with a numpy array, use the following:

In [2]:
x = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print("x: \n{}\n".format(x))
print("First row of x: {}".format(x[0]))
print("The shape of x: {}".format(np.shape(x)))

x: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

First row of x: [0 1 2 3]
The shape of x: (3L, 4L)


### Other Matrices

While np.array is useful, there are many ways to generate common matrices. These functions take as input a tuple () that holds the shape of the numpy array to be generated.

In [3]:
zr = np.zeros((3, 3))
print("Matrix of zeroes of shape (3, 3): \n{}\n".format(zr))

ones = np.ones((3, 3))
print("Matrix of ones of shape (3, 3): \n{}\n".format(ones))

rand = np.random.random((3, 3))
print("Random matrix of shape (3, 3): \n{}\n".format(rand))

seq = np.arange(6)
print("Sequence vector of shape (6,), starting from 0: \n{}\n".format(seq))

Matrix of zeroes of shape (3, 3): 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matrix of ones of shape (3, 3): 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Random matrix of shape (3, 3): 
[[0.54011192 0.21949186 0.44769121]
 [0.66704716 0.96413676 0.15186834]
 [0.90407785 0.70459047 0.32329915]]

Sequence vector of shape (6,), starting from 0: 
[0 1 2 3 4 5]



## Mathematical Operations

There are many built-in mathematical functions to work with matrices that you will find useful in future projects. Here, basic python operations (such as + and -) operate elementwise between a numpy array and a constant OR another array of the **same** shape.

In [ ]:
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

print("A - B (Elementwise Subtraction): \n{}\n".format(A - B))
print("A * B (Elementwise Multiplication): \n{}\n".format(A * B))
print("A ** 3 (Elementwise Power): \n{}\n".format(A**3))

Another useful function is the np.dot() function. This acts as a dot product function (outputing a scalar) on two 1D vectors, and matrix multiplication if the matrices are 2D or higher.

In [ ]:
print("Dot Product of A and B: {}\n".format(np.dot(A, B)))

C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
D = np.array([[20],[30],[40]])

print("Shape of C: {}".format(np.shape(C)))
print("Shape of D: {}".format(np.shape(D)))
print("Matrix Product of C and D: \n{}".format(np.dot(C, D)))
print("Final Shape: {}\n".format(np.shape(np.dot(C, D))))

You can also transpose a matrix quite easily.

In [ ]:
print("D: \n{}\n".format(D))
print("D Transpose: \n{}\n".format(D.T))

### Problem 1

Given two numpy arrays A with shape (m, n) and B with shape (m, n), calculate: $$AB^TA$$ No loops allowed!

In [ ]:
def prob_one(A, B):
    
    # Insert Code Here
    raise NotImplementedError
    

In [ ]:
A = np.array([[1, 3, 5], [2, 4, 6], [1, 1, 1]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

student_sol = prob_one(A, B)
official_sol = [[164, 382, 600], [224, 520, 816], [60, 138, 216]]
flag = np.allclose(student_sol, official_sol)
if flag:
    print("Your solution is correct: \n{}\n".format(student_sol))
    print("Good work!")
else:
    print("Your solution is incorrect: \n{}".format(student_sol))

### Preexisting Functions

There are many more built-in functions in numpy that run operations such as sum, max, and min on the matrices. In addition, you can specify the axis by which you want to apply a specific operation - if no axis is given the operation will be applied on the entire matrix.

In [ ]:
print("Sum of all elements in C: {}\n".format(np.sum(C)))
print("Max of all elements in C: {}\n".format(np.amax(C)))
print("Min of all elements in C: {}\n".format(np.amin(C)))
print("Sum of columns of C: \n{}\n".format(np.sum(C, axis = 1)))
print("Max of rows of C: \n{}\n".format(np.amax(C, axis = 0)))

## Problem 2

Given two matrices A of shape (m, n) and B of shape (m, n), find the index of the smallest element across each row of A and each row of B, and sum all the indices together. The result should be a scalar.

Hint: Search the numpy documentation for the "argmin" function.

In [ ]:
def prob_two(A, B):
    
    # Insert Code Here
    raise NotImplementedError
    

In [ ]:
A = np.array([[1, 2, 3], [4, 6, 5], [9, 8, 7]])
B = np.array([[0, 3, 5], [2, 3, 1], [5, 3, 9]])

student_sol = prob_two(A, B)
official_sol = 5
flag = np.allclose(student_sol, official_sol)
if flag:
    print("Your solution is correct: \n{}\n".format(student_sol))
    print("Good work!")
else:
    print("Your solution is incorrect: \n{}".format(student_sol))

### Working with array shapes

If your numpy array isn't in the correct shape or orientation, numpy offers a slew of functions to make manipulating this fairly simple! The reshape function takes a new shape tuple, and adjusts each dimension to fit the new shape.

In [ ]:
A = np.array([1, 3, 5, 7, 9])

print("A: {}\n".format(A))
print("A, now with shape (5, 1): \n{}".format(A.reshape(5, 1)))

Multidimensional arrays can also be flattened into 1D variants, where each row is appended to the end of the previous row.

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("A: \n{}\n".format(A))
print("Flattened representation of A \n{}".format(A.flatten()))

## Indexing

Sometimes, you want to get specific sections or elements from a numpy array. These support indexing just like python lists!

In [ ]:
A = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])

print("First row of A: {}".format(A[0]))
print("First element of first row of A: {}\n".format(A[0][0]))

For multidimensional arrays, sections can be taken using the following "colon" notation.

In [ ]:
print("First two rows, last two columns of A: \n{}\n".format(A[:2, 3:]))
print("Last two columns of A: \n{}\n".format(A[:, 3:]))

Numpy arrays also support boolean indexing - you can assign values to sections of an array that fulfill a specific condition without having to iterate using loops.

In [ ]:
A[A > 6] = 0
print("All elements that are greater than 6 are now 0: \n{}\n".format(A))

## Problem 3

Given a matrix A, flatten the last three columns of A and set all negative values to 0.

In [ ]:
def prob_three(A):
    
    # Insert Code Here
    raise NotImplementedError

In [ ]:
A = np.array([[1, -2, 3, 4, -5], [-6, -7, -8, -9, -10], [-11, 12, 13, -14, 15]])

student_sol = prob_three(A)
official_sol = np.array([3, 4, 0, 0, 0, 0, 13, 0, 15])
flag = np.allclose(student_sol, official_sol)
if flag:
    print("Your solution is correct: \n{}\n".format(student_sol))
    print("Good work!")
else:
    print("Your solution is incorrect: \n{}".format(student_sol))